
name: "Rotas ITX"
slug: "rotas-itx"
version: "1.0.0"

ingress: true
panel_icon: mdi:web
panel_title: "Rotas ITX"

startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

options: {}
schema: {}
