name: "Gerador de Rotas ITX"
slug: "rotas-itx"
version: "1.0.0"
description: "Aplicação Python independente hospedada no HA"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ingress: false
ports:
  5050/tcp: 5050
options: {}
schema: {}
